### ISSUE TITLE
Multiple Input options for transformers in spreadsheet needed for implementing pumps into SESMG system

### ISSUE THREAD

**Issue by DV-Bongingi** [SESMG/SESMG#114]
Hi everyone, 
I'm relatively new to Github and SESMG but already had the chance to sketch an energy system according to the docs and to chrklemm's advices. 
For my Masterthesis, I'd like to set up an energy system for seawater desalination with renewable energys. Therefore I need to implement (high pressure) pumps with significant electricity demand. This means, that for the transformer as pump, I need to define two different inputs in the spreadsheet as the pump needs electricity and water intake.

Can anyone give me advices or support me, how to solve the problem?

I'm happy to contribute, share and develop my content as far as possible and meaningful.
I attached a screenshot of my sketch for better understanding.
![image](https://user-images.githubusercontent.com/104626933/175304289-f565367e-0d41-4157-9b8d-df9e6b56721d.png)

Your help would be much appreciated.
Kind regards
Dominik

**Comment by DV-Bongingi** [comment]
Hi Gregor,

thanks a lot for your fast respond and comments :)

The main principle of water desalination with reverse-osmosis (RO) ist to push the salty water with high pressure through a membrane, so that salt and other unwanted content gets filtered and thus potable water emerges on the one side and high salty concentrate on the other. This pressure is supplied by pumps, which have a significant electricity demand.

I need to somehow join these components (different stages of water, electricity and concentrate) in transformers.
 
I don't have exact numbers for my efficiencies yet, but as the transformers will be pumps, I was thinking of defining an electricity input with the power capacitiy limit of the pump (e. g. 2 MW) and to set its efficiency of transforming electricity into a certain flow rate (m³/h) as one of the two possible efficiency-options in terms of the SESMG. 
As I don't have any OEMOF or SESMG experience yet, I don't know how to seperate (or combine) the two different material or energy flows (water/concentrate and electricity) in the SESMG to be able to calculate the flow rate of desalinated water with given renewable energy suppliers on the one hand, but also being able to calculate energy demand and the total (specific) costs of the system (in €/m³ and €/kWh used).

With PR you mean a pull request? What is it and what do I have to do to open one up, meanin which information do you need?

All I did so far was downloading and testing (succesfully) the SESMG, reading the docs, sketching the above energy system with my interpretation of the SESMG docs and then filling out the excel spreadsheet according to my sketch and the possible input options of the spreadsheet. This is where my problem with the multiple inputs at the transformers occured. So I haven't started the SESMG programm itself yet, as my energy system didn't fit the requirements of the spreadsheet.
By the way, I also drew sketches of the process that are less complex for the first step by step implemantations like this one (still needs some adjustments):
![image](https://user-images.githubusercontent.com/104626933/175775386-c14b4ee4-a3d0-4476-8794-74a6c6a04424.png)

It might well be that I missunderstood the way how to build up a system for the SESMG with my sketch and that there is an other way around my issue, but this is why I need help :)


What do you mean with Branch? 

Would it be possible for you to make an online appointment via zoom/teams/jitsi or similar so that I can explain the issue to you and we can discuss solutions together?
That would be much easier for me. 

I very much appreciate your support! 
Please tell me if I can do anything else to help you to better understand my usecase!?

**Comment by GregorBecker** [comment]
Hi Dominik, 
I think it makes sense to schedule a short meeting regarding the PR (yes your assumption that it is a pull request is correct) as well as the implementation in SESMG. Feel free to contact me briefly via email to look for a timeslot.
My email: Gregor.becker@fh-muenster.de
With kind regards 
Gregor

**Comment by DV-Bongingi** [comment]
Hi Gregor, 
I send you an email from my private adresse as I can't access my FH-Mail account atm due to the current system problems of the FHM. 
If you can't access your mail account neither or did not receive my mail, please let me know and I can ask chrklemm to kindly pass you my mobile number.
Kind regards,
Dominik

**Comment by GregorBecker** [comment]
If the two input transformer worked in the application of @DV-Bongingi  without errors, we still have to include it in the documentation. @DV-Bongingi do you feel confident to do this documentation or do you need a briefing on the SESMG's documentation?

**Comment by DV-Bongingi** [comment]
So far everything works fine. A briefing on the SESMG's docs would be much appreciated, as I haven't worked on it before.

**Comment by chrklemm** [comment]
@DV-Bongingi I can give you a short introduction, I'll get in touch with you by mail.

**Comment by chrklemm** [comment]
is implemented in the master-branch, but must be merged to dev-branch for JOSS publication @GregorBecker

**Comment by GregorBecker** [comment]
done
