### ISSUE TITLE
Functional extension until the publication of the SESMG

### ISSUE THREAD

**Issue by GregorBecker** [SESMG/SESMG#124]
- [ ] #114 
- [x] #111 
- [x] Set up Codecov, Code climate, Scrutinizer, ... @GregorBecker 
- [ ] Add Anergy systems
- [ ] implement a new GUI @jtock 
- [x] discussion installation procedure 
- [x] fork external packages for pip installation

**Comment by chrklemm** [comment]
We should also discuss the instalation procdedure!

**Comment by chrklemm** [comment]
We should create forks of the packages included in the repository (feedinlib, demandlib, ...) so that we can pip install that forks, instead of storing it in the SESMG-Repository

**Comment by chrklemm** [comment]
duplication of existing issues => labeled respective issues and closed this issue
