### ISSUE TITLE
Features for the Upscaling Tool

### ISSUE THREAD

**Issue by GregorBecker** [SESMG/SESMG#129]
**Code of Conduct**
- [x] Hereby I consent to the [CODE_OF_CONDUCT](https://github.com/chrklemm/SESMG/blob/master/CODE_OF_CONDUCT.md)[^1]

Issue, which is used to record the missing aspects of the upscaling tool.

- [x] rename the column "living area" (pre-scenario) to gross building area.
- [x] /program_files/urban_district_upscaling/pre_processing.py - REFACTORING occupants=building['occupants per unit'] 
- [x] only one standard parameter sheet, since "switch criterion" works.
- [x] Implement distinction of roof types.
- [x] add units row in pre-scenario file
- [x] "Label" instead of "component" in the central sheet.
- [x] Open Fred as an optional possibility in the upscaling GUI. If the Open Fred data is entered in the GUI, then only the missing temperatures from the pre-scenario are imported, otherwise, all columns are imported.
- [x] heat demand and electricity demand each only one sheet in standard parameter
- [x] vorlauftemperatur im Gebäude vorgeben in der US-Tabelle dann für WP und Solarthermie übernehmen?
- [x] length of the geoth. Probe, heat extraction - in die US-Tabelle ist Standortbezogen
- [x] building specific electricity purchase prices
- [x]  building specific electricity purchase emissions
- [x] adding an fireplace as an component (How to model the impact on heat demand?) - effects us sheet, standard parameter sheet, Transformer.py
[^1]: Fill in a x between the brackets to check the check box.

**Comment by janik257** [comment]
vorlauftemperatur im Gebäude vorgeben in der US-Tabelle dann für WP und Solarthermie übernehmen?

**Comment by janik257** [comment]
length of the geoth. Probe, heat extraction - in die US-Tabelle ist Standortbezogen

**Comment by janik257** [comment]
- [ ] Central solar plants (PV, ST) don't work within US tool. Busses are created but Sources aren't created (see sheet 3 _us_sheet.xlsx_)
- [ ] _electricity_exchange, battery, power_to_gas, timeseries_source_ are central technologies that cannot be deleted of sheet 3 _us_sheet.xlsx_. The following error message appears: **..\program_files\urban_district_upscaling\components\Central_components.py", line 280, in central_comp
    if central.loc[(central["technology"] == "battery")]["active"].values[0] == 1:
IndexError: index 0 is out of bounds for axis 0 with size 0**

**Comment by chrklemm** [comment]
Please check which of the open points are JOSS relevant. For not-joss relevant items please create individual wish-list issues @GregorBecker

**Comment by GregorBecker** [comment]
I've done the JOSS relevant features requested by @janik257. Since the rest are new features I'm labeling the issue with wish list and new feature.

**Comment by GregorBecker** [comment]
done and merged
