### ISSUE TITLE
Bug: first streamlit run (dev-branch)

### ISSUE THREAD

**Issue by jtock** [SESMG/SESMG#139]
Mail can be added when opening streamlit with the terminal for the first time. App can not be started without reacting to the message below.

Work around needs to be added.

streamlit run GUI_streamlit.py
"""
2022-11-28 11:44:35.905 INFO    numexpr.utils: NumExpr defaulting to 8 threads.

  👋 Welcome to Streamlit!

  If you're one of our development partners or you're interested in getting
  personal technical support or Streamlit updates, please enter your email
  address below. Otherwise, you may leave the field blank.

  Email:  
"""

**Comment by GregorBecker** [comment]
done
