### ISSUE TITLE
Add: Installation for Apple M1 / M2 users

### ISSUE THREAD

**Issue by jtock** [SESMG/SESMG#140]
Installation process does not work for users with Apple M1 / M2 Chips.

Identified reasons (probably not all):
- not possible to install python3.7 without workaround (https://stackoverflow.com/questions/70315418/installing-python3-7-macbook-air-m1-problem) 
- directory / location of installed packages by brew differ from other chip users. (Intel: opt/local/ , M1/M2: opt/homebrew/)
- issues with opening _geoslib.cpython

**Comment by chrklemm** [comment]
add clarification, that the installation is not working for M1/2 chip-users in the documentation for the joss publication

**Comment by jtock** [comment]
Not necessary anymore after changing the mac installation and removing tkinter.
