### ISSUE TITLE
Developing new GUI with streamlit

### ISSUE THREAD

**Issue by jtock** [SESMG/SESMG#141]
Sub GUIs
- [x] Main GUI - parameter input
- [x] Main GUI - start page
- [x] US GUI - parameter input
- [x] US GUI - start page
- [x] US GUI - result page
- [x] Result Processing - input
- [x] Result Processing - start page
- [ ] Result Processing - results / sub-results
- [x] Demo Tool - input
- [x] Demo Tool - start page
- [x] Demo Tool - results

**Comment by jtock** [comment]
DH clustering & DH precalc has currently no function in the new GUI. Needs to be checked if functions work in backend code with @GregorBecker 

No need for Show Graph anymore

**Comment by chrklemm** [comment]
why is there no need to show the graph anymore, @jtock . I think it is very usefull.

**Comment by jtock** [comment]
Demo Tool with basic, but all necessary, functions implemented. Advanced functionality needs to be further developed and implemented.
Therefore see: #160

**Comment by jtock** [comment]
done
