### ISSUE TITLE
Implement Anergy Networks

### ISSUE THREAD

**Issue by jtock** [SESMG/SESMG#142]
Anergy systems to be added

**Comment by chrklemm** [comment]
do we have an update for that @GregorBecker?

**Comment by GregorBecker** [comment]
I started to implement a distinction between energy and anergy networks but ran out of time due to other tasks. As soon as there is more time again I will dedicate myself to this energy system component again but currently I have to keep it on the wishlist.

**Comment by GregorBecker** [comment]
We need to document the use of anergy networks, but the implementation has already been carried out in the dev-branch.

**Comment by jtock** [comment]
done and documented
