### ISSUE TITLE
Features for the train station project

### ISSUE THREAD

**Issue by janik257** [SESMG/SESMG#145]
**Code of Conduct**
- [x] Hereby I consent to the [CODE_OF_CONDUCT][^1]

**Describe the solution you'd like**
- [x]  year of construction for building components - _effects us sheet and Insulation.py_
- [x] modelling two or more components in order to consider heat supply of a building (status quo) - _effects us sheet, pre_processing.py_
- [x] implement existing renovation 
- [x] building pellet heating system 
- [x] air to air heat pump
- [ ] building specific results - _effects post_processing.py_

[^1]: Fill in a x between the brackets to check the check box.

**Comment by janik257** [comment]
_Sekundäre (oder auch „ergänzende“) Heizsysteme verbrauchen im Mittel 39 kWh/(m²*a). Der Deckungsanteil am Gesamt-Energieverbauch des zu beheizenden Gebäudes beträgt 33 Prozent. Bei 23 Prozent der Gebäude ist der Endenergieverbrauch des sekundären Heizsystems höher als der Verbrauch des primären Heizsystems, d.h., eigentlich stellt die Zusatzheizung
das primäre Heizsystem dar. Der Substitutionseffekt, durch die Nutzung einer Zusatzheizung bewirkt eine Endenergieeinsparung des primären Heizsystems von etwa 28 Prozent gegenüber Gebäuden ohne ergänzendes Heizsystem._
Quelle: https://www.co2online.de/fileadmin/co2/research/zusatzheizung-studie.pdf

**Proposal:** If the building has a stove, the heat demand is reduced by X percent. Thus, X kWh is covered by the stove and X kWh by the primary heating system.

**Comment by janik257** [comment]
In order to model two or more components within the status quo, we could add a column which contains the capacitiy of a technology. However we dont know the capacity and have to assume them. Another problem is, that an existing capacity could result to an undersupply.

**Comment by GregorBecker** [comment]
> In order to model two or more components within the status quo, we could add a column which contains the capacitiy of a technology. However we dont know the capacity and have to assume them. Another problem is, that an existing capacity could result to an undersupply (two runs necessary) and the costs arent considerd (instead of existing capacity rather min = max investment).

the consideration of already existing nominal powers should be already implemented, I will check it in the next days.

**Comment by GregorBecker** [comment]
> > In order to model two or more components within the status quo, we could add a column which contains the capacitiy of a technology. However we dont know the capacity and have to assume them. Another problem is, that an existing capacity could result to an undersupply (two runs necessary) and the costs arent considerd (instead of existing capacity rather min = max investment).
> 
> the consideration of already existing nominal powers should be already implemented, I will check it in the next days.

done

**Comment by GregorBecker** [comment]
moved to #214
