### ISSUE TITLE
Update requirements.txt for Streamlit GUI

### ISSUE THREAD

**Issue by jtock** [SESMG/SESMG#148]
@GregorBecker to test after finishing st GUI

Missing packages 
- [x] streamlit (+ error #139)
- [x] streamlit-aggrid

list to be continued

**Comment by jtock** [comment]
MacOS: need to check if graphviz needs to be installed globally

**Comment by GregorBecker** [comment]
i have added streamlit and streamlit aggrid to the requirements file and tested the installation.

**Comment by janik257** [comment]
please add streamlit extras

**Comment by GregorBecker** [comment]
Are there still packages missing? @jtock If not please close this issue.
