### ISSUE TITLE
Code Climate Badges in Readme

### ISSUE THREAD

**Issue by GregorBecker** [SESMG/SESMG#149]
**Code of Conduct**
- [x] Hereby I consent to the [CODE_OF_CONDUCT](https://github.com/chrklemm/SESMG/blob/master/CODE_OF_CONDUCT.md)[^1]  

**Describe the bug**
There seems to be something wrong with CodeClimate's badges. At least they are not updated. 

@chrklemm  since your are the admin can you search for the badges markdown code on code climate?

[^1]: Fill in a x between the brackets to check the check box.

**Comment by chrklemm** [comment]
I updated the badges, but there might be problems updating that value, since i wasn't able to grant permanent access to the repository for codeclimate (https://docs.codeclimate.com/docs/approve-code-climate-as-a-third-party-application-in-github)
