### ISSUE TITLE
problems during the installation process

### ISSUE THREAD

**Issue by benblankenstein** [SESMG/SESMG#155]
**Code of Conduct**
- [x] Hereby I consent to the [CODE_OF_CONDUCT](https://github.com/chrklemm/SESMG/blob/master/CODE_OF_CONDUCT.md)[^1]  

- [x] Difficulty finding the download button; describe in more detail where it is located (green '<> Code' button, 'Download ZIP' at the bottom).
- [x] Difficulty finding the link for the download of CBC. CBC Solver is located under Open-Source Solvers --> 'Download from our portal'.
- [x] Difficulty installing Graphviz, because version graphviz-2.38.msi does not exist; not clear which version to download, as there is a difference between 32 and 64 bit and EXE installer and ZIP archive.

**Comment by chrklemm** [comment]
maybe it would be usefull to make a video where we explain the installation procedure in detail?

**Comment by GregorBecker** [comment]
After the Windows installation, the user is asked to enter the email address. Thus, streamlit does not automatically find the .streamlit file on Windows.
