### ISSUE TITLE
Missing info: initial capacity >= minimal capacity of a storage

### ISSUE THREAD

**Issue by jtock** [SESMG/SESMG#159]
**Code of Conduct**
- [x] Hereby I consent to the [CODE_OF_CONDUCT](https://github.com/SESMG/SESMG/blob/master/CODE_OF_CONDUCT.md)[^1]  

Initial capacity has to be at least as high as the minimal capacity of a storage.

ToDos:
- [x] Add an information to the docu (@chrklemm , @janik257)
- [x] Update Demo Tool 
- [x] Change values in model_definition_example
- [x] Add comment to model_definition_example
- [x] Add `return_list.append([component["sequences"][(i, "flow")]]) KeyError: 'sequences'` to the troubleshooting

**Comment by chrklemm** [comment]
I have never come along with this problem during my own modeling. I think we should add an information to the docu:

"initial capacity: Specifies how far the storage is loaded at time 0 of the simulation. Value must be between 0 and 1. _The initial capacity value must be higher than the 'min. capacity' value_ ." (https://spreadsheet-energy-system-model-generator.readthedocs.io/en/latest/02.02.00_application.html#storages)

**Comment by jtock** [comment]
Done with minimal changes.
