### ISSUE TITLE
3rd component in competition constraints

### ISSUE THREAD

**Issue by DV-Bongingi** [SESMG/SESMG#165]
**Code of Conduct**
- [x] Hereby I consent to the [CODE_OF_CONDUCT](https://github.com/SESMG/SESMG/blob/master/CODE_OF_CONDUCT.md)

**Is your feature request related to a problem? Please describe.**
Finding the optimum composition for a ground-mounted PV-system regarding the size (installed power) of different orientations (more than two) within constraint area available.

**Describe the solution you'd like**
It would be nice to let 3 different components compete against each other for the same limited resource. This would be useful for sizing ground-mounted PV-systems with 3 different possible orientations (e. g. east, south/north, west) within the same limited area available. Although their specific area use (kW/m²) might nearly be the same, the effect on energy production will differ for each orientation. Maybe it only needs adding a third component in the inputsheet and related code? 

Another example would be the competition of more than two different windturbines within the same area available.

**Comment by jtock** [comment]
Thank you for your idea, @DV-Bongingi!
Right now there is no way to use this function in the SESMG version. We can think about implementing it in a future version. I will add it to the feature list.
Greetings

**Comment by DV-Bongingi** [comment]
Ok no problem, thats why I put it on the wish list.
