### ISSUE TITLE
wind turbine without production

### ISSUE THREAD

**Issue by jtock** [SESMG/SESMG#166]
**Code of Conduct**
x Hereby I consent to the [CODE_OF_CONDUCT](https://github.com/SESMG/SESMG/blob/master/CODE_OF_CONDUCT.md)[^1]  

Wind turbines are now used for production although there is an investment. Even if there are extreme negative excess and positive shortage costs.
Does not run with the model_definition_example sheet. Used the E-126/4200.

I set min and max capacity on the same value to run a simulation. 
There is no investment in the wind turbine if I switch the criteria. Shouldn't the emission optimized run invest in the system as well?

**Comment by janik257** [comment]
In the source code, the time series have been replaced by absolute values (see Source.py lines 301-304). Probably someone is fixing the problem @GregorBecker.
