### ISSUE TITLE
Documentation build is failing

### ISSUE THREAD

**Issue by chrklemm** [SESMG/SESMG#167]
**Code of Conduct**
- [x] Hereby I consent to the [CODE_OF_CONDUCT](https://github.com/SESMG/SESMG/blob/master/CODE_OF_CONDUCT.md) 

The build of the documentation is failing since the commit 23e67e61162e931e1fecd759bc290a7649cbc0d3 two days ago, which is odd, because nothing has been changed in the documentation files. I wasn't able to figure out what the error is. Has someone an idea what the reason could be?

**Comment by jtock** [comment]
Got the same issue. Maybe a problem with readthedocs itself which will be fixed soon and autoupdate afterwards.

**Comment by chrklemm** [comment]
You're probably right, obsiously other RTD users are having the same problem: https://github.com/readthedocs/readthedocs.org/issues/10150

**Comment by chrklemm** [comment]
The RTD-update has been rolled back, as many users were having that issue. However, the update will be re-enroled in a few weeks. 

Our documentation is beeing build correctly for now, but we should definitly have an eye on it.

**Comment by GregorBecker** [comment]
Since there has been no more disruption in the past few weeks, this issue is temporarily closed.
