### ISSUE TITLE
Pareto Point 1

### ISSUE THREAD

**Issue by jtock** [SESMG/SESMG#170]
There is a bug in the result processing while sorting / creating the pareto point 0. It can be seen in the given diagram. The same problem occurs in the parteto.csv

<img width="991" alt="Bildschirmfoto 2023-03-31 um 16 51 15" src="https://user-images.githubusercontent.com/102952410/229154764-4ef40ce1-637a-4512-85ab-024928f80093.png">

**Comment by GregorBecker** [comment]
This error resulted from an incorrect model definition. 
Done.
