### ISSUE TITLE
Re-Factor Result-Processing (Energy Amount)

### ISSUE THREAD

**Issue by chrklemm** [SESMG/SESMG#173]
**Code of Conduct**
- [x] Hereby I consent to the [CODE_OF_CONDUCT](https://github.com/SESMG/SESMG/blob/master/CODE_OF_CONDUCT.md)[^1]

@jtock, @GregorBecker and I were discussing about refactoring the energy-amount-processing. We could possibly introduce some kind of "component-type-key" within the model definition, which can be used for balancing. 

Maybe this could be a long term task for @benblankenstein ?

**Comment by GregorBecker** [comment]
Moved to #211
