### ISSUE TITLE
Names of the rows and columns in the Standard Parameter Sheet

### ISSUE THREAD

**Issue by FranziKoert** [SESMG/SESMG#201]
**Code of Conduct**
- [^1] Hereby I consent to the [CODE_OF_CONDUCT](https://github.com/SESMG/SESMG/blob/master/CODE_OF_CONDUCT.md)[^1]

**Is your feature request related to a problem? Please describe.**
The names of the technologies or the columns of the Standard Parameter Sheet are not always self-explaining. 

Examples:
- where is the difference between central and fixed photovoltaic source
- come columens contain parameter names divided by '_', other names are just divided by spaces
- there are more examples 

**Describe the solution you'd like**
- use a uniformed naming for different technologies and parameters

**Comment by GregorBecker** [comment]
done
