### ISSUE TITLE
Prevent wrong Python version in installation

### ISSUE THREAD

**Issue by jtock** [SESMG/SESMG#205]
### Discussed in https://github.com/SESMG/SESMG/discussions/204

<div type='discussions-op-text'>

<sup>Originally posted by **nbeine** November 30, 2023</sup>
Hello everyone,

As the extended installation is recommended in the installation guide, I carried that one out.
Even though the working python versions (3.7 - 3.9) are stated in guide, there may emerge conflicts with the installation:

I had already installed python on my computer (as version 3.10). This version (and newer versions as well) trigger conflicts with the h5py version 3.6.0, which is demanded in the requirements.txt. 

My idea/suggestion is the following:

Even though you state the possible python versions in your manual, it may be advantageous to change the way you query the version in the developer installation. When entering 3.10 (or newer) in the developer installation command, the installation may be aborted and the user may receive a warning, that the installed python version leads to conflicts. This may save a lot of time when searching the error cause.

Like stated before, you mention the working versions. But maybe stress the possible conflicts more or build in a query/warning. 

Cheers,
@nbeine</div>

We can add two options from my point of view:
- An additional info in the installation cmd which warns the user 
- A logic which kills the process, if the wrong Python version is typed in

**Comment by GregorBecker** [comment]
Linux closes the console automatically if the python version is incorrect. We should either include this in troubleshooting or fix it.

**Comment by jtock** [comment]
done in #6489583 for mac and linux

**Comment by jtock** [comment]
done for windows in 7d7d7f8f24db19cf407a747adf614e9a028392ac
