### ISSUE TITLE
Tuple error in program_files.preprocessing in data_preparation

### ISSUE THREAD

**Issue by FranziKoert** [SESMG/SESMG#209]
**Describe the bug**
   """ elif data_prep == 'slicing B':
        slicing.timeseries_slicing2(n_days=int(days_per_cluster),
                                    nodes_data=nodes_data,
                                    period=cluster_period) """

Behind this part of the code and also the elif condition before was a comma, that turned additional returns from sclicing.timeseries_slicing automatically into a tupel.

**Comment by GregorBecker** [comment]
fixed and merged
