### ISSUE TITLE
Adjusting the time series 

### ISSUE THREAD

**Issue by TimSteinort** [SESMG/SESMG#224]
**Adjusting the time series**

**Describe the bug**
If you adjust the time series in the model definition by changing the start or end date in the energysystem sheet, the periods must be 8760 hours and cannot be changed.
Reducing the periods will result in a sequence error. 

**To Reproduce**
1. Go to energysystem sheet
2. Adjust the end date to 01.01.2012 23:00:00
3. Change periods to 24h

**Expected behavior**
There may be a variable that sets the number of periods to the fixed value of 8760. Cutting the last lines of the time and weather series caused another error.

**Error**

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - SESMG-version: v1.0.0

[^1]: Fill in a x between the brackets to check the check box.

**Comment by GregorBecker** [comment]
By adjusting the length of the time series and weather data sheets in the model definition and reducing the energy demand to a representative value for 24 hours, the error was resolved.

A description will be added to the documentation to prevent these error causes in the future.
