### ISSUE TITLE
An error occurs when SESMG is in a subdirectory containing spaces.

### ISSUE THREAD

**Issue by GregorBecker** [SESMG/SESMG#46]
- [ ] Fix the Error for all operating systems

**Comment by chrklemm** [comment]
check wether this error still occurs. If yes, set focus on describing it in the troubleshooting @chrklemm (windows), @GregorBecker (macOS)

tbd: 31.01.2023

**Comment by GregorBecker** [comment]
to be checked on Linux, done for MacOS and Windows
