### ISSUE TITLE
Checking the upscaling tool

### ISSUE THREAD

**Issue by janik257** [SESMG/SESMG#68]
- [x]  it is not possible to deactivate the disctrict heat and electricity bus?
- [x]  issues with excel and the expression TRUE for central components
- [x]  explaining that you only are allowed to write "yes" not "Yes" for components
- [x] gchp has to be filled with values >0 otherwise the energysystem is not complete
- [ ]  explaining to change the periods in standard parameters otherwise "sequences" error appears
- [x] create a pre_scenario in order to test the urban upscaling tool

**Comment by chrklemm** [comment]
Maybe we should use digits (1, 0) instead of "yes" and "no" anyway?

**Comment by janik257** [comment]
yes, good idea!

**Comment by chrklemm** [comment]
last open point is no longer valid => closed
