### ISSUE TITLE
Switch Criteria

### ISSUE THREAD

**Issue by janik257** [SESMG/SESMG#94]
The function "Switch Criteria" is shown in the documentation but not explained. The function does not work correctly yet or? We need to fix the function or push it out of the master branch and the documentation.

**Comment by GregorBecker** [comment]
Fix investment constraint costs have been added in the "dev" branch, the switch criterion function is now usable again. Missing documentation has been added to Issue #123. Can we close this issue now?

**Comment by chrklemm** [comment]
@GregorBecker did you check, whether the criterion switch is working correctly? We had some issues in the past

**Comment by GregorBecker** [comment]
An error was fixed in the pareto curve algorithm, is this also implemented in the normal criterion switch? @GregorBecker

**Comment by GregorBecker** [comment]
done
